name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Java installieren
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Projekt bauen
        run: ./gradlew build

      - name: Tests ausführen
        run: ./gradlew test

      - name: Formatierung prüfen
        run: ./gradlew check