name: Java CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code holen
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: ./gradlew build

      - name: Tests ausführen
        run: ./gradlew test

      - name: Format prüfen
        run: ./gradlew check